# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c38f0e61cca05b2b6c1657136cd077938b00b8d3393d856700680a412a7a65fcf76fa6962147203f17739d691a98a8958a052da1865372877c8fe2c1e1fd50a

test:
  secret_key_base: f9ca5e480a07483c5d8c0a9af97ec8aeb2b2f75cfa61e28e9a895af4894fd94f089844ee7ef06ed97f7e411ccde6c496bf20a9008f2cae3e3cbc9693e9ca0cef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
